import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { Suspense } from "react";
import Loading from "./loading";

const geistSans = Noto_Serif_Bengali({
  variable: "--font-geist-sans",
  subsets: ["latin", "bengali"],
});

const geistMono = Noto_Serif_Bengali({
  variable: "--font-geist-mono",
  subsets: ["latin", "bengali"],
});

export const metadata = {
  title: "Bazar Dor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="bn"
      className={`${geistSans.variable} ${geistMono.variable} bg-[#F0F5F0] antialiased`}
    >
      <body className="min-h-screen flex flex-col justify-between">
        <Suspense fallback={<Loading/>}>
          <Navbar />
            <main className="grow">{children}</main>
          <Footer />
        </Suspense>
      </body>
    </html>
  );
}